use crate::matchers::n1::*;
use crate::matchers::n2::*;
use crate::matchers::n3::*;
use crate::matchers::n4::*;
use crate::matchers::n5::*;
use crate::pattern_matcher::{GrammarPattern, PatternCategory, PatternMatcher};
use crate::types::ConjugationPattern;

macro_rules! declare_patterns {
    (
        $(
            $variant:ident {
                name: $name:expr,
                matcher_fn: $matcher_fn:path,
                priority: $priority:expr,
                category: $category:path,
                jlpt: $jlpt:expr,
                conjugation: $conj:path $(,)?
            }
        ),* $(,)?
    ) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum Pattern {
            $($variant,)*
        }

        impl Pattern {
            pub fn grammar_pattern(&self) -> GrammarPattern {
                match self {
                    $(Pattern::$variant => GrammarPattern {
                        name: $name,
                        tokens: $matcher_fn(),
                        priority: $priority,
                        category: $category,
                        jlpt_level: $jlpt,
                    },)*
                }
            }

            pub fn conjugation_pattern(&self) -> ConjugationPattern {
                match self {
                    $(Pattern::$variant => $conj,)*
                }
            }

            pub fn all() -> Vec<Pattern> {
                vec![$(Pattern::$variant,)*]
            }
        }
    }
}

declare_patterns! {
    // ========== N5 PATTERNS (38 total) ==========
    DictionaryForm {
        name: "dictionary_form",
        matcher_fn: dictionary_form,
        priority: 1,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::Dictionary,
    },
    MasuForm {
        name: "masu_form",
        matcher_fn: masu_ending,
        priority: 4,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::MasuForm,
    },
    ShortNegative {
        name: "short_negative",
        matcher_fn: short_negative,
        priority: 4,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::Negative,
    },
    PoliteNegative {
        name: "polite_negative",
        matcher_fn: polite_negative,
        priority: 4,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::PoliteNegative,
    },
    PastTense {
        name: "past_tense",
        matcher_fn: ta_form,
        priority: 4,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::Past,
    },
    ShortPastNegative {
        name: "short_past_negative",
        matcher_fn: short_past_negative,
        priority: 4,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::PastNegative,
    },
    PolitePast {
        name: "polite_past",
        matcher_fn: polite_past_ending,
        priority: 4,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::PolitePast,
    },
    Deshita {
        name: "deshita",
        matcher_fn: deshita,
        priority: 4,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::Deshita,
    },
    TaiForm {
        name: "tai_form",
        matcher_fn: tai_form,
        priority: 5,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::TaiForm,
    },
    TakunaiForm {
        name: "takunai_form",
        matcher_fn: takunai_form,
        priority: 6,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::TakunaiForm,
    },
    TakattaForm {
        name: "takatta_form",
        matcher_fn: takatta_form,
        priority: 6,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::TakattaForm,
    },
    TeForm {
        name: "te_form",
        matcher_fn: te_form,
        priority: 3,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::TeForm,
    },
    TeIru {
        name: "te_iru",
        matcher_fn: te_iru,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::TeIru,
    },
    TeKara {
        name: "te_kara",
        matcher_fn: te_kara,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::TeKara,
    },
    TeKudasai {
        name: "te_kudasai",
        matcher_fn: te_kudasai,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::TeKudasai,
    },
    TeMoIi {
        name: "te_mo_ii",
        matcher_fn: te_mo_ii,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::TeMoIi,
    },
    TeWaIkenai {
        name: "te_wa_ikenai",
        matcher_fn: te_wa_ikenai,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::TeWaIkenai,
    },
    NaideKudasai {
        name: "naide_kudasai",
        matcher_fn: naide_kudasai,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::NaideKudasai,
    },
    MasenKa {
        name: "masen_ka",
        matcher_fn: masen_ka,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::MasenKa,
    },
    PoliteVolitional {
        name: "polite_volitional",
        matcher_fn: polite_volitional,
        priority: 6,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::PoliteVolitional,
    },
    MashouKa {
        name: "mashou_ka",
        matcher_fn: mashou_ka,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::MashouKa,
    },
    TaKotoGaAru {
        name: "ta_koto_ga_aru",
        matcher_fn: ta_koto_ga_aru,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::TaKotoGaAru,
    },
    Sugiru {
        name: "sugiru",
        matcher_fn: sugiru,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::Sugiru,
    },
    TsumoriDesu {
        name: "tsumori_desu",
        matcher_fn: tsumori_desu,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::TsumoriDesu,
    },
    HouGaIi {
        name: "hou_ga_ii",
        matcher_fn: hou_ga_ii,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::HouGaIi,
    },
    Deshou {
        name: "deshou",
        matcher_fn: deshou,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::Deshou,
    },
    MadaTeImasen {
        name: "mada_te_imasen",
        matcher_fn: mada_te_imasen,
        priority: 12,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::MadaTeImasen,
    },
    NDesu {
        name: "n_desu",
        matcher_fn: n_desu,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::NDesu,
    },
    NodeVerb {
        name: "node_verb",
        matcher_fn: node_verb,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::Node,
    },
    NodeAdjective {
        name: "node_adjective",
        matcher_fn: node_adjective,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::Node,
    },
    NodeNominal {
        name: "node_nominal",
        matcher_fn: node_nominal,
        priority: 4,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::Node,
    },
    NiIku {
        name: "ni_iku",
        matcher_fn: ni_iku,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::NiIku,
    },
    MaeNi {
        name: "mae_ni",
        matcher_fn: mae_ni,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n5",
        conjugation: ConjugationPattern::MaeNi,
    },
    Adjective {
        name: "adjective",
        matcher_fn: adjective,
        priority: 1,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::Dictionary,
    },
    AdjectivePast {
        name: "adjective_past",
        matcher_fn: adjective_past,
        priority: 2,
        category: PatternCategory::Conjugation,
        jlpt: "n5",
        conjugation: ConjugationPattern::Dictionary,
    },

    // ========== N4 PATTERNS (62 total) ==========
    TeMiru {
        name: "te_miru",
        matcher_fn: te_miru,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TeMiru,
    },
    TeShimau {
        name: "te_shimau",
        matcher_fn: te_shimau,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TeShimau,
    },
    TeAru {
        name: "te_aru",
        matcher_fn: te_aru,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TeAru,
    },
    TeKureru {
        name: "te_kureru",
        matcher_fn: te_kureru,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TeKureru,
    },
    TeKudasaru {
        name: "te_kudasaru",
        matcher_fn: te_kudasaru,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TeKudasaru,
    },
    TeAgeru {
        name: "te_ageru",
        matcher_fn: te_ageru,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TeAgeru,
    },
    TeOku {
        name: "te_oku",
        matcher_fn: te_oku,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TeOku,
    },
    TeMorau {
        name: "te_morau",
        matcher_fn: te_morau,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TeMorau,
    },
    TeMo {
        name: "te_mo",
        matcher_fn: te_mo,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TeMo,
    },
    TeSumimasen {
        name: "te_sumimasen",
        matcher_fn: te_sumimasen,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TeSumimasen,
    },
    TeKureteArigatou {
        name: "te_kurete_arigatou",
        matcher_fn: te_kurete_arigatou,
        priority: 13,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TeKureteArigatou,
    },
    TeYokatta {
        name: "te_yokatta",
        matcher_fn: te_yokatta,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TeYokatta,
    },
    TeItadakemasenKa {
        name: "te_itadakemasen_ka",
        matcher_fn: te_itadakemasen_ka,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TeItadakemasenKa,
    },
    TariSuruSingle {
        name: "tari_suru_single",
        matcher_fn: tari_suru_single,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TariForm,
    },
    TariSuru {
        name: "tari_suru",
        matcher_fn: tari_suru,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TariForm,
    },
    BaConditional {
        name: "ba_conditional",
        matcher_fn: ba_conditional,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::BaConditional,
    },
    TaraConditional {
        name: "tara_conditional",
        matcher_fn: tara_conditional,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TaraConditional,
    },
    TaraDou {
        name: "tara_dou",
        matcher_fn: tara_dou,
        priority: 12,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::TaraDou,
    },
    BaYokatta {
        name: "ba_yokatta",
        matcher_fn: ba_yokatta,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::BaYokatta,
    },
    PotentialGodan {
        name: "potential_godan",
        matcher_fn: potential_godan,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Potential,
    },
    PotentialGaVerb {
        name: "potential_ga_verb",
        matcher_fn: potential_ga_verb,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Potential,
    },
    PotentialGaIchidan {
        name: "potential_ga_ichidan",
        matcher_fn: potential_ga_ichidan,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Potential,
    },
    PassiveIchidan {
        name: "passive_ichidan",
        matcher_fn: passive_ichidan,
        priority: 4,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Passive,
    },
    PassiveGodan {
        name: "passive_godan",
        matcher_fn: passive_godan,
        priority: 4,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Passive,
    },
    Causative {
        name: "causative",
        matcher_fn: causative,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Causative,
    },
    CausativePassive {
        name: "causative_passive",
        matcher_fn: causative_passive,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::CausativePassive,
    },
    ShortVolitional {
        name: "short_volitional",
        matcher_fn: short_volitional,
        priority: 6,
        category: PatternCategory::Conjugation,
        jlpt: "n4",
        conjugation: ConjugationPattern::ShortVolitional,
    },
    Imperative {
        name: "imperative",
        matcher_fn: imperative,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Imperative,
    },
    Nagara {
        name: "nagara",
        matcher_fn: nagara,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Nagara,
    },
    NakuchaIkenai {
        name: "nakucha_ikenai",
        matcher_fn: nakucha_ikenai,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::NakuchaIkenai,
    },
    MustNakereba {
        name: "must_nakereba",
        matcher_fn: must_nakereba,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Must,
    },
    MustNakuteWa {
        name: "must_nakute_wa",
        matcher_fn: must_nakute_wa,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Must,
    },
    Naide {
        name: "naide",
        matcher_fn: naide,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Naide,
    },
    NakuteMoIi {
        name: "nakute_mo_ii",
        matcher_fn: nakute_mo_ii,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::NakuteMoIi,
    },
    HazuDesu {
        name: "hazu_desu",
        matcher_fn: hazu_desu,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::HazuDesu,
    },
    Tagaru {
        name: "tagaru",
        matcher_fn: tagaru,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Tagaru,
    },
    Yasui {
        name: "yasui",
        matcher_fn: yasui,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Yasui,
    },
    Nikui {
        name: "nikui",
        matcher_fn: nikui,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Nikui,
    },
    Nasai {
        name: "nasai",
        matcher_fn: nasai,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Nasai,
    },
    GaHoshii {
        name: "ga_hoshii",
        matcher_fn: ga_hoshii,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::GaHoshii,
    },
    ShikaNai {
        name: "shika_nai",
        matcher_fn: shika_nai,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::ShikaNai,
    },
    ToIu {
        name: "to_iu",
        matcher_fn: to_iu,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::ToIu,
    },
    DictionaryTo {
        name: "dictionary_to",
        matcher_fn: dictionary_to,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::DictionaryTo,
    },
    ToIi {
        name: "to_ii",
        matcher_fn: to_ii,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::ToIi,
    },
    KotoNiSuru {
        name: "koto_ni_suru",
        matcher_fn: koto_ni_suru,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::KotoNiSuru,
    },
    KotoNiNaru {
        name: "koto_ni_naru",
        matcher_fn: koto_ni_naru,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::KotoNiNaru,
    },
    Noni {
        name: "noni",
        matcher_fn: noni,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Noni,
    },
    Nara {
        name: "nara",
        matcher_fn: nara,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Nara,
    },
    Shi {
        name: "shi",
        matcher_fn: shi,
        priority: 3,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Shi,
    },
    KaDouKa {
        name: "ka_dou_ka",
        matcher_fn: ka_dou_ka,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::KaDouKa,
    },
    Mitai {
        name: "mitai",
        matcher_fn: mitai,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Mitai,
    },
    MitaiAdjNoun {
        name: "mitai_adj_noun",
        matcher_fn: mitai_adj_noun,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::Mitai,
    },
    KamoShirenai {
        name: "kamo_shirenai",
        matcher_fn: kamo_shirenai,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::KamoShirenai,
    },
    KamoShirenaiAdjNoun {
        name: "kamo_shirenai_adj_noun",
        matcher_fn: kamo_shirenai_adj_noun,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::KamoShirenai,
    },
    KamoShiremasen {
        name: "kamo_shiremasen",
        matcher_fn: kamo_shiremasen,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::KamoShirenai,
    },
    KamoShiremasenAdjNoun {
        name: "kamo_shiremasen_adj_noun",
        matcher_fn: kamo_shiremasen_adj_noun,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::KamoShirenai,
    },
    ONiNaru {
        name: "o_ni_naru",
        matcher_fn: o_ni_naru,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::ONiNaru,
    },
    SouDesuAppearance {
        name: "sou_desu_appearance",
        matcher_fn: sou_desu_appearance,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::SouDesuAppearance,
    },
    SouDesuHearsay {
        name: "sou_desu_hearsay",
        matcher_fn: sou_desu_hearsay,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::SouDesuHearsay,
    },
    SouDesuHearsayNa {
        name: "sou_desu_hearsay_na",
        matcher_fn: sou_desu_hearsay_na,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n4",
        conjugation: ConjugationPattern::SouDesuHearsay,
    },

    // ========== N3 PATTERNS (60 total) ==========
    Hajimeru {
        name: "hajimeru",
        matcher_fn: hajimeru,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Hajimeru,
    },
    WoHajime {
        name: "wo_hajime",
        matcher_fn: wo_hajime,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::WoHajime,
    },
    Rashii {
        name: "rashii",
        matcher_fn: rashii,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Rashii,
    },
    YouNiNaru {
        name: "you_ni_naru",
        matcher_fn: you_ni_naru,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::YouNiNaru,
    },
    YouNiSuru {
        name: "you_ni_suru",
        matcher_fn: you_ni_suru,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::YouNiSuru,
    },
    YouNiStandalone {
        name: "you_ni_standalone",
        matcher_fn: you_ni_standalone,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::YouNi,
    },
    TameNi {
        name: "tame_ni",
        matcher_fn: tame_ni,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::TameNi,
    },
    Zu {
        name: "zu",
        matcher_fn: zu,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Zu,
    },
    Gachi {
        name: "gachi",
        matcher_fn: gachi,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Gachi,
    },
    PpoiSplit {
        name: "ppoi_split",
        matcher_fn: ppoi_split,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Ppoi,
    },
    PpoiCompound {
        name: "ppoi_compound",
        matcher_fn: ppoi_compound,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Ppoi,
    },
    TaBakari {
        name: "ta_bakari",
        matcher_fn: ta_bakari,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::TaBakari,
    },
    TaMonoDa {
        name: "ta_mono_da",
        matcher_fn: ta_mono_da,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::TaMonoDa,
    },
    TaMonoDesu {
        name: "ta_mono_desu",
        matcher_fn: ta_mono_desu,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::TaMonoDa,
    },
    NiChigainai {
        name: "ni_chigainai",
        matcher_fn: ni_chigainai,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::NiChigainai,
    },
    Mama {
        name: "mama",
        matcher_fn: mama,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Mama,
    },
    Furi {
        name: "furi",
        matcher_fn: furi,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Furi,
    },
    NaiUchiNi {
        name: "nai_uchi_ni",
        matcher_fn: nai_uchi_ni,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::NaiUchiNi,
    },
    ToShitara {
        name: "to_shitara",
        matcher_fn: to_shitara,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::ToShitara,
    },
    TsumorideDe {
        name: "tsumori_de",
        matcher_fn: tsumori_de,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::TsumorideDe,
    },
    Bakari {
        name: "bakari",
        matcher_fn: bakari,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Bakari,
    },
    KiriPast {
        name: "kiri_past",
        matcher_fn: kiri_past,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Kiri,
    },
    KiriNoun {
        name: "kiri_noun",
        matcher_fn: kiri_noun,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Kiri,
    },
    Kawari {
        name: "kawari",
        matcher_fn: kawari,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Kawari,
    },
    OkageDe {
        name: "okage_de",
        matcher_fn: okage_de,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::OkageDe,
    },
    Sae {
        name: "sae",
        matcher_fn: sae,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Sae,
    },
    SaeBa {
        name: "sae_ba",
        matcher_fn: sae_ba,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::SaeBa,
    },
    Koso {
        name: "koso",
        matcher_fn: koso,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Koso,
    },
    Masaka {
        name: "masaka",
        matcher_fn: masaka,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Masaka,
    },
    Mushiro {
        name: "mushiro",
        matcher_fn: mushiro,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Mushiro,
    },
    Sudeni {
        name: "sudeni",
        matcher_fn: sudeni,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Sudeni,
    },
    Tsui {
        name: "tsui",
        matcher_fn: tsui,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Tsui,
    },
    Doushitemo {
        name: "doushitemo",
        matcher_fn: doushitemo,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Doushitemo,
    },
    Seizei {
        name: "seizei",
        matcher_fn: seizei,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Seizei,
    },
    Douyara {
        name: "douyara",
        matcher_fn: douyara,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Douyara,
    },
    Kaette {
        name: "kaette",
        matcher_fn: kaette,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Kaette,
    },
    Sarani {
        name: "sarani",
        matcher_fn: sarani,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Sarani,
    },
    Wazawaza {
        name: "wazawaza",
        matcher_fn: wazawaza,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Wazawaza,
    },
    Nakanaka {
        name: "nakanaka",
        matcher_fn: nakanaka,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Nakanaka,
    },
    Ittai {
        name: "ittai",
        matcher_fn: ittai,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Ittai,
    },
    // Suffixes (2)
    TekiSuffix {
        name: "teki_suffix",
        matcher_fn: teki_suffix,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Teki,
    },
    TateSuffix {
        name: "tate_suffix",
        matcher_fn: tate_suffix,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Tate,
    },
    NiYotte {
        name: "ni_yotte",
        matcher_fn: ni_yotte,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::NiYotte,
    },
    NiYoruTo {
        name: "ni_yoru_to",
        matcher_fn: ni_yoru_to,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::NiYoruTo,
    },
    OiteCompound {
        name: "oite_compound",
        matcher_fn: oite_compound,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Oite,
    },
    OiteSplit {
        name: "oite_split",
        matcher_fn: oite_split,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Oite,
    },
    Toshite {
        name: "toshite",
        matcher_fn: toshite,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Toshite,
    },
    NiKansuru {
        name: "ni_kansuru",
        matcher_fn: ni_kansuru,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::NiKansuru,
    },
    // No More Than (1)
    Suginai {
        name: "suginai",
        matcher_fn: suginai,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Suginai,
    },
    ToTomoni {
        name: "to_tomoni",
        matcher_fn: to_tomoni,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::ToTomoni,
    },
    TeHajimete {
        name: "te_hajimete",
        matcher_fn: te_hajimete,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::TeHajimete,
    },
    Gurai {
        name: "gurai",
        matcher_fn: gurai,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Gurai,
    },
    BaHodo {
        name: "ba_hodo",
        matcher_fn: ba_hodo,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::BaHodo,
    },
    // Limitation (2)
    Kagiru {
        name: "kagiru",
        matcher_fn: kagiru,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Kagiru,
    },
    Mai {
        name: "mai",
        matcher_fn: mai,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n3",
        conjugation: ConjugationPattern::Mai,
    },

    // ========== N2 PATTERNS (70 total) ==========
    // Adverbs (17)
    Toutei {
        name: "toutei",
        matcher_fn: toutei,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Toutei,
    },
    Yoppodo {
        name: "yoppodo",
        matcher_fn: yoppodo,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Yoppodo,
    },
    Iyoiyo {
        name: "iyoiyo",
        matcher_fn: iyoiyo,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Iyoiyo,
    },
    Sekkaku {
        name: "sekkaku",
        matcher_fn: sekkaku,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Sekkaku,
    },
    Yappari {
        name: "yappari",
        matcher_fn: yappari,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Yappari,
    },
    Narubeku {
        name: "narubeku",
        matcher_fn: narubeku,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Narubeku,
    },
    Tashika {
        name: "tashika",
        matcher_fn: tashika,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Tashika,
    },
    ManIchiKanji {
        name: "man_ichi",
        matcher_fn: man_ichi_kanji,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::ManIchi,
    },
    ManIchiKana {
        name: "man_ichi_kana",
        matcher_fn: man_ichi_kana,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::ManIchi,
    },
    NanishiroKanji {
        name: "nanishiro_kanji",
        matcher_fn: nanishiro_kanji,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Nanishiro,
    },
    NanishiroKana {
        name: "nanishiro_kana",
        matcher_fn: nanishiro_kana,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Nanishiro,
    },
    SoreniShitemo {
        name: "sorenishitemo",
        matcher_fn: soreni_shitemo,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::SoreniShitemo,
    },
    Tachimachi {
        name: "tachimachi",
        matcher_fn: tachimachi,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Tachimachi,
    },
    ItsunoManikaKanji {
        name: "itsunomanika_split",
        matcher_fn: itsunomanika_split,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Itsunomanika,
    },
    ItsunoManikaKana {
        name: "itsunomanika",
        matcher_fn: itsunomanika,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Itsunomanika,
    },
    Aete {
        name: "aete",
        matcher_fn: aete,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Aete,
    },
    Semete {
        name: "semete",
        matcher_fn: semete,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Semete,
    },
    // Unavoidably/Properly (3)
    YamouezuVerb {
        name: "yamuoezu_verb",
        matcher_fn: yamuoezu_verb,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Yamuoezu,
    },
    RouNi {
        name: "rou_ni",
        matcher_fn: rou_ni,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::RouNi,
    },
    SasuganiSplit {
        name: "sasugani_split",
        matcher_fn: sasugani_split,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Sasugani,
    },
    // After All (2)
    NantottemmoKanji {
        name: "nantoittemo_split_kanji",
        matcher_fn: nantoittemo_split_kanji,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Nantoittemo,
    },
    NantottemmoKana {
        name: "nantoittemo_adverb_split",
        matcher_fn: nantoittemo_adverb_split,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Nantoittemo,
    },
    // Ability/Impossibility (3)
    Kaneru {
        name: "kaneru",
        matcher_fn: kaneru,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Kaneru,
    },
    Kanenai {
        name: "kanenai",
        matcher_fn: kanenai,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Kanenai,
    },
    Tamaranai {
        name: "tamaranai",
        matcher_fn: tamaranai,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Tamaranai,
    },
    // Without/Consist Of (3)
    NaideSumu {
        name: "naide_sumu_split",
        matcher_fn: naide_sumu_split,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::NaideSumu,
    },
    KaraNaru {
        name: "kara_naru",
        matcher_fn: kara_naru,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::KaraNaru,
    },
    YoriShikataGanaiKanji {
        name: "yori_shikata_ganai",
        matcher_fn: yori_shikata_ganai,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::YoriShikataGanai,
    },
    YoriShikataGanaiKana {
        name: "yori_shikata_ganai_kana",
        matcher_fn: yori_shikata_ganai_kana,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::YoriShikataGanai,
    },
    // After Doing (1)
    TaUeDe {
        name: "ta_ue_de",
        matcher_fn: ta_ue_de,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::TaUeDe,
    },
    // Correspond To (2)
    NiAtaruCompound {
        name: "ni_ataru_compound",
        matcher_fn: ni_ataru_compound,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::NiAtaru,
    },
    NiAtaruKanji {
        name: "ni_ataru_compound_kanji",
        matcher_fn: ni_ataru_kanji,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::NiAtaru,
    },
    // Like/Through (3)
    // GotoshiKana {
    //     name: "gotoshi_kana",
    //     matcher_fn: gotoshi,
    //     priority: 6,
    //     category: PatternCategory::Construction,
    //     jlpt: "n2",
    //     conjugation: ConjugationPattern::Gotoshi,
    // },
    GotoshiKanji {
        name: "gotoshi_kanji",
        matcher_fn: gotoshi_kanji,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Gotoshi,
    },
    TsuujiteVerbKanji {
        name: "tsuujite_verb_kanji",
        matcher_fn: tsuujite_verb_kanji,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Tsuujite,
    },
    // TsuujiteVerbKana {
    //     name: "tsuujite_verb_kana",
    //     matcher_fn: tsuujite_verb_kana,
    //     priority: 7,
    //     category: PatternCategory::Construction,
    //     jlpt: "n2",
    //     conjugation: ConjugationPattern::Tsuujite,
    // },
    // Amount To (1)
    Noboru {
        name: "noboru",
        matcher_fn: noboru,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Noboru,
    },
    // While/And (2)
    GateraSplit {
        name: "gatera_split",
        matcher_fn: gatera_split,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Gatera,
    },
    Oyobi {
        name: "oyobi",
        matcher_fn: oyobi,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Oyobi,
    },
    // Perhaps Because/Therefore (2)
    SeiKa {
        name: "sei_ka",
        matcher_fn: sei_ka,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::SeiKa,
    },
    YueniSplit {
        name: "yueni_split",
        matcher_fn: yueni_split,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Yueni,
    },
    IppouDewaSplit {
        name: "ippou_dewa_split",
        matcher_fn: ippou_dewa_split,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::IppouDewa,
    },
    MonoNo {
        name: "mono_no",
        matcher_fn: mono_no,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::MonoNo,
    },
    MonoNoSplit {
        name: "mono_no_split",
        matcher_fn: mono_no_split,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::MonoNo,
    },
    KuseNiSplit {
        name: "kuse_ni_split",
        matcher_fn: kuse_ni_split,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::KuseNi,
    },
    KaketeHaCompound {
        name: "kaketeha_compound",
        matcher_fn: kaketeha_compound,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::KaketeHa,
    },
    ItaruMadeKana {
        name: "itaru_made",
        matcher_fn: itaru_made,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::ItaruMade,
    },
    ItaruMadeKanji {
        name: "itaru_made_kanji",
        matcher_fn: itaru_made_kanji,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::ItaruMade,
    },
    NiItaruMadeKana {
        name: "ni_itaru_made",
        matcher_fn: ni_itaru_made,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::ItaruMade,
    },
    NiItaruMadeKanji {
        name: "ni_itaru_made_kanji",
        matcher_fn: ni_itaru_made_kanji,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::ItaruMade,
    },
    IgaiNo {
        name: "igai_no",
        matcher_fn: igai_no,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::IgaiNo,
    },
    BaIiNoni {
        name: "ba_ii_noni",
        matcher_fn: ba_ii_noni,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::BaIiNoni,
    },
    BaYoiNoniSplit {
        name: "ba_yoi_noni_split",
        matcher_fn: ba_yoi_noni_split,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::BaIiNoni,
    },
    WakeDesu {
        name: "wake_desu",
        matcher_fn: wake_desu,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::WakeDesu,
    },
    WakeDa {
        name: "wake_da",
        matcher_fn: wake_da,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::WakeDesu,
    },
    YouNaKiGaSuru {
        name: "you_na_ki_ga_suru",
        matcher_fn: you_na_ki_ga_suru,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::YouNaKiGaSuru,
    },
    NiKiWoTsukeru {
        name: "ni_ki_wo_tsukeru",
        matcher_fn: ni_ki_wo_tsukeru,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::NiKiWoTsukeru,
    },
    BetsuniNaiSplit {
        name: "betsuni_nai_split",
        matcher_fn: betsuni_nai_split,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::BetsuniNai,
    },
    WakeNiwaIkanaiShort {
        name: "wake_niwa_ikanai_short",
        matcher_fn: wake_niwa_ikanai_short,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::WakeNiwaIkanai,
    },
    NaiWakeNiwaIkanaiShort {
        name: "nai_wake_niwa_ikanai_short",
        matcher_fn: nai_wake_niwa_ikanai_short,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::NaiWakeNiwaIkanai,
    },
    DewaNaiDarouKaFullSplit {
        name: "dewa_nai_darou_ka_full_split",
        matcher_fn: dewa_nai_darou_ka_full_split,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::DewaNaiDarouKa,
    },
    ToIuWakeDewaNaiCompound {
        name: "to_iu_wake_dewa_nai_compound",
        matcher_fn: to_iu_wake_dewa_nai_compound,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::ToIuWakeDewaNai,
    },
    NiKoshitaKotoWaNai {
        name: "ni_koshita_koto_wa_nai",
        matcher_fn: ni_koshita_koto_wa_nai,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::NiKoshitaKotoWaNai,
    },
    SashitsukaenaiKana {
        name: "sashitsukaenai",
        matcher_fn: sashitsukaenai,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Sashitsukaenai,
    },
    SashitsukaenaiKanji {
        name: "sashitsukaenai_kanji",
        matcher_fn: sashitsukaenai_kanji,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::Sashitsukaenai,
    },
    ToIttemKanji {
        name: "to_ittemo",
        matcher_fn: to_ittemo,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::ToIttemo,
    },
    ToIttemKana {
        name: "to_ittemo_kana",
        matcher_fn: to_ittemo_kana,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::ToIttemo,
    },
    GaKiNiNaru {
        name: "ga_ki_ni_naru",
        matcher_fn: ga_ki_ni_naru,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::GaKiNiNaru,
    },
    OmouYouNi {
        name: "omou_you_ni",
        matcher_fn: omou_you_ni,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::OmouYouni,
    },
    MonoDesukara {
        name: "mono_desukara",
        matcher_fn: mono_desukara,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::MonoDesukara,
    },
    MonoDakara {
        name: "mono_dakara",
        matcher_fn: mono_dakara,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n2",
        conjugation: ConjugationPattern::MonoDesukara,
    },

    // ========== N1 PATTERNS (107 total) ==========
    Meku {
        name: "meku",
        matcher_fn: meku,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Meku,
    },
    MekuCompound {
        name: "meku_compound",
        matcher_fn: meku_compound,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Meku,
    },
    Mamire {
        name: "mamire",
        matcher_fn: mamire,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Mamire,
    },
    MamireCompound {
        name: "mamire_compound",
        matcher_fn: mamire_compound,
        priority: 5,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Mamire,
    },
    Zukume {
        name: "zukume",
        matcher_fn: zukume,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Zukume,
    },
    Ppanashi {
        name: "ppanashi",
        matcher_fn: ppanashi,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Ppanashi,
    },
    Kiwamaru {
        name: "kiwamaru",
        matcher_fn: kiwamaru,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Kiwamaru,
    },
    Kiwamarinai {
        name: "kiwamarinai",
        matcher_fn: kiwamarinai,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Kiwamaru,
    },
    Beku {
        name: "beku",
        matcher_fn: beku,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Beku,
    },
    Bekarazu {
        name: "bekarazu",
        matcher_fn: bekarazu,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Bekarazu,
    },
    Majiki {
        name: "majiki",
        matcher_fn: majiki,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Majiki,
    },
    Nari {
        name: "nari",
        matcher_fn: nari,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Nari,
    },
    YaInaya {
        name: "ya_inaya",
        matcher_fn: ya_inaya,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::YaInaya,
    },
    YaInayaSingle {
        name: "ya_inaya_single",
        matcher_fn: ya_inaya_single,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::YaInaya,
    },
    GaHayaiKa {
        name: "ga_hayai_ka",
        matcher_fn: ga_hayai_ka,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::GaHayaiKa,
    },
    GaSaigo {
        name: "ga_saigo",
        matcher_fn: ga_saigo,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::GaSaigo,
    },
    Gotoki {
        name: "gotoki",
        matcher_fn: gotoki,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Gotoki,
    },
    WoKawakiriNi {
        name: "wo_kawakiri_ni",
        matcher_fn: wo_kawakiri_ni,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::WoKawakiriNi,
    },
    WoMotte {
        name: "wo_motte",
        matcher_fn: wo_motte,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::WoMotte,
    },
    Nakushiteha {
        name: "nakushiteha",
        matcher_fn: nakushiteha,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Nakushiteha,
    },
    Nashini {
        name: "nashini",
        matcher_fn: nashini,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Nashini,
    },
    Naradewa {
        name: "naradewa",
        matcher_fn: naradewa,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Naradewa,
    },
    NiTaru {
        name: "ni_taru",
        matcher_fn: ni_taru,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::NiTaru,
    },
    Toatte {
        name: "toatte",
        matcher_fn: toatte,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Toatte,
    },
    Katagata {
        name: "katagata",
        matcher_fn: katagata,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Katagata,
    },
    WoKagiriNi {
        name: "wo_kagiri_ni",
        matcher_fn: wo_kagiri_ni,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::WoKagiriNi,
    },
    WoHete {
        name: "wo_hete",
        matcher_fn: wo_hete,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::WoHete,
    },
    WoOshite {
        name: "wo_oshite",
        matcher_fn: wo_oshite,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::WoOshite,
    },
    WoFumaete {
        name: "wo_fumaete",
        matcher_fn: wo_fumaete,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::WoFumaete,
    },
    TeYamanai {
        name: "te_yamanai",
        matcher_fn: te_yamanai,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::TeYamanai,
    },
    ToOmoikiya {
        name: "to_omoikiya",
        matcher_fn: to_omoikiya,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::ToOmoikiya,
    },
    ToAreba {
        name: "to_areba",
        matcher_fn: to_areba,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::ToAreba,
    },
    TaTokoroDe {
        name: "ta_tokoro_de",
        matcher_fn: ta_tokoro_de,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::TaTokoroDe,
    },
    DeAre {
        name: "de_are",
        matcher_fn: de_are,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::DeAre,
    },
    ToWaIe {
        name: "to_wa_ie",
        matcher_fn: to_wa_ie,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::ToWaIe,
    },
    YouGa {
        name: "you_ga",
        matcher_fn: you_ga,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::YouGa,
    },
    NaiMadeMo {
        name: "nai_made_mo",
        matcher_fn: nai_made_mo,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::NaiMadeMo,
    },
    NagaraMo {
        name: "nagara_mo",
        matcher_fn: nagara_mo,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::NagaraMo,
    },
    DewaArumaishi {
        name: "dewa_arumaishi",
        matcher_fn: dewa_arumaishi,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::DewaArumaishi,
    },
    ToShitaTokoroDe {
        name: "to_shita_tokoro_de",
        matcher_fn: to_shita_tokoro_de,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::ToShitaTokoroDe,
    },
    ToIedomo {
        name: "to_iedomo",
        matcher_fn: to_iedomo,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::ToIedomo,
    },
    TomoNaruto {
        name: "tomo_naruto",
        matcher_fn: tomo_naruto,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::TomoNaruto,
    },
    NiTaenai {
        name: "ni_taenai",
        matcher_fn: ni_taenai,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::NiTaenai,
    },
    NiSokushite {
        name: "ni_sokushite",
        matcher_fn: ni_sokushite,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::NiSokushite,
    },
    ToAimatte {
        name: "to_aimatte",
        matcher_fn: to_aimatte,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::ToAimatte,
    },
    WoYosoni {
        name: "wo_yosoni",
        matcher_fn: wo_yosoni,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::WoYosoni,
    },
    TemoSashitsukaenai {
        name: "temo_sashitsukaenai",
        matcher_fn: temo_sashitsukaenai,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::TemoSashitsukaenai,
    },
    WoKinjienai {
        name: "wo_kinjienai",
        matcher_fn: wo_kinjienai,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::WoKinjienai,
    },
    WoYoginakusareru {
        name: "wo_yoginakusareru",
        matcher_fn: wo_yoginakusareru,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::WoYoginakusareru,
    },
    TeKaratoiumono {
        name: "te_karatoiumono",
        matcher_fn: te_karatoiumono,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::TeKaratoiumono,
    },
    NimoMashite {
        name: "nimo_mashite",
        matcher_fn: nimo_mashite,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::NimoMashite,
    },
    NiHikikae {
        name: "ni_hikikae",
        matcher_fn: ni_hikikae,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::NiHikikae,
    },
    IkanDe {
        name: "ikan_de",
        matcher_fn: ikan_de,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Ikan,
    },
    IkanNiyotte {
        name: "ikan_niyotte",
        matcher_fn: ikan_niyotte,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Ikan,
    },
    IkanShidai {
        name: "ikan_shidai",
        matcher_fn: ikan_shidai,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Ikan,
    },
    IkanNoDa {
        name: "ikan_no_da",
        matcher_fn: ikan_no_da,
        priority: 11,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Ikan,
    },
    Taritomo {
        name: "taritomo",
        matcher_fn: taritomo,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Taritomo,
    },
    KiraiGaAru {
        name: "kirai_ga_aru",
        matcher_fn: kirai_ga_aru,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::KiraiGaAru,
    },
    ShimatsuDa {
        name: "shimatsu_da",
        matcher_fn: shimatsu_da,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::ShimatsuDa,
    },
    ShimatsuDatta {
        name: "shimatsu_datta",
        matcher_fn: shimatsu_datta,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::ShimatsuDa,
    },
    Warini {
        name: "warini",
        matcher_fn: warini,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Warini,
    },
    Wariniha {
        name: "wariniha",
        matcher_fn: wariniha,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Warini,
    },
    Sura {
        name: "sura",
        matcher_fn: sura,
        priority: 6,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::DeSura,
    },
    DeSura {
        name: "de_sura",
        matcher_fn: de_sura,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::DeSura,
    },
    KotoNashini {
        name: "koto_nashini",
        matcher_fn: koto_nashini,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::KotoNashini,
    },
    KaiMoNaku {
        name: "kai_mo_naku",
        matcher_fn: kai_mo_naku,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::KaiMoNaku,
    },
    DakeMashi {
        name: "dake_mashi",
        matcher_fn: dake_mashi,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::DakeMashi,
    },
    NaideWaSumanai {
        name: "naide_wa_sumanai",
        matcher_fn: naide_wa_sumanai,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::NaideWaSumanai,
    },
    NagaraniUmare {
        name: "nagarani_umare",
        matcher_fn: nagarani_umare,
        priority: 9,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Nagarani,
    },
    NagaraniUmareShite {
        name: "nagarani_umare_shite",
        matcher_fn: nagarani_umare_shite,
        priority: 10,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Nagarani,
    },
    NagaraniSplit {
        name: "nagarani_split",
        matcher_fn: nagarani_split,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Nagarani,
    },
    NagaraniShite {
        name: "nagarani_shite",
        matcher_fn: nagarani_shite,
        priority: 8,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::Nagarani,
    },
    HaOroka {
        name: "ha_oroka",
        matcher_fn: ha_oroka,
        priority: 7,
        category: PatternCategory::Construction,
        jlpt: "n1",
        conjugation: ConjugationPattern::HaOroka,
    },
}

pub fn create_pattern_matcher() -> PatternMatcher<ConjugationPattern> {
    let mut matcher = PatternMatcher::new();

    let matcher_patterns: Vec<_> = Pattern::all()
        .into_iter()
        .map(|p| (p.grammar_pattern(), p.conjugation_pattern()))
        .collect();

    matcher.add_patterns(matcher_patterns);

    matcher
}

pub fn get_all_patterns() -> Vec<(GrammarPattern, ConjugationPattern, &'static str)> {
    Pattern::all()
        .into_iter()
        .map(|p| {
            (
                p.grammar_pattern(),
                p.conjugation_pattern(),
                p.grammar_pattern().jlpt_level,
            )
        })
        .collect()
}
